//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyParentApi.Shared {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StrRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrRes() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyParentApi.Shared.StrRes", typeof(StrRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário e senhas não coincidem, tente novamente..
        /// </summary>
        public static string StrAuthInvalid {
            get {
                return ResourceManager.GetString("StrAuthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro no banco de dados, contate um administrador!.
        /// </summary>
        public static string StrDatabaseError {
            get {
                return ResourceManager.GetString("StrDatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Família não encontrada..
        /// </summary>
        public static string StrFamilyNotFound {
            get {
                return ResourceManager.GetString("StrFamilyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não é um membro da familia {1}.
        /// </summary>
        public static string StrFamilyNotMember {
            get {
                return ResourceManager.GetString("StrFamilyNotMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível inserir um novo usuário no banco de dados..
        /// </summary>
        public static string StrNewUserCannotSave {
            get {
                return ResourceManager.GetString("StrNewUserCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível inserir uma Role para o usuário {0}..
        /// </summary>
        public static string StrNewUserRoleNotCreated {
            get {
                return ResourceManager.GetString("StrNewUserRoleNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagem enviada para {0}.
        /// </summary>
        public static string StrNoteSent {
            get {
                return ResourceManager.GetString("StrNoteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Family Created.
        /// </summary>
        public static string StrOperationNewFamily {
            get {
                return ResourceManager.GetString("StrOperationNewFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Family Member.
        /// </summary>
        public static string StrOperationNewFamilyMember {
            get {
                return ResourceManager.GetString("StrOperationNewFamilyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New User Registered.
        /// </summary>
        public static string StrOperationNewUser {
            get {
                return ResourceManager.GetString("StrOperationNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password Recovery Requested.
        /// </summary>
        public static string StrOperationRecoveryRequest {
            get {
                return ResourceManager.GetString("StrOperationRecoveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro durante a criação de uma requisição de recuperação de senha..
        /// </summary>
        public static string StrRecoveryError {
            get {
                return ResourceManager.GetString("StrRecoveryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email de recuperação foi encaminhado para {0}..
        /// </summary>
        public static string StrRecoverySent {
            get {
                return ResourceManager.GetString("StrRecoverySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro interno no processo do repositório: {0}.
        /// </summary>
        public static string StrRepError {
            get {
                return ResourceManager.GetString("StrRepError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notificação.
        /// </summary>
        public static string StrTitleAdvertise {
            get {
                return ResourceManager.GetString("StrTitleAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string StrTitleError {
            get {
                return ResourceManager.GetString("StrTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        public static string StrTitleNone {
            get {
                return ResourceManager.GetString("StrTitleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso.
        /// </summary>
        public static string StrTitleWarning {
            get {
                return ResourceManager.GetString("StrTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O email {0} já foi utilizado, caso necessário faça o processo de recuperação de senha..
        /// </summary>
        public static string StrUserAlreadyExists {
            get {
                return ResourceManager.GetString("StrUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível criar o usuário para {0}..
        /// </summary>
        public static string StrUserCannotCreate {
            get {
                return ResourceManager.GetString("StrUserCannotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} já faz parte de uma família e não pode ser convidado..
        /// </summary>
        public static string StrUserHasFamily {
            get {
                return ResourceManager.GetString("StrUserHasFamily", resourceCulture);
            }
        }
    }
}
